
# Workflow name
name: 'Build and Test'

# Event for the workflow
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Check copyright license on files"]
    types:
      - completed

# List of jobs
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 8.6.1
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check Copyright license
        uses: ./.github/workflows/check-copyright-license
      - name: Build package
        run: pnpm build
      - name: Test
        run: pnpm test -- --coverage --bail --detectOpenHandles
#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v3